= Analyse-Klassendiagramm
#image("Klassendiagramm.svg")
Im Rahmen der Analyse und Modellierung unseres Systems wurden verschiedene objektorientierte Analysemuster gezielt eingesetzt, um wiederkehrende Strukturprobleme effizient und nachvollziehbar zu lösen. Diese Muster bieten bewährte Lösungen für typische Modellierungssituationen und fördern eine klare, wartbare Struktur des Klassendiagramms.

Ein zentrales Beispiel ist die Trennung zwischen Werkzeugbeschreibung und Werkzeugexemplar, die dem Analysemuster „Exemplartyp“ folgt. Hierbei werden allgemeine, für alle Exemplare eines Werkzeugs identische Informationen wie Name, Hersteller und Wartungsanforderungen in der Beschreibungsklasse erfasst. Individuelle Merkmale wie Seriennummer, Zustand oder Baujahr werden hingegen dem konkreten Exemplar zugewiesen. Dieses Muster vermeidet Redundanz, erleichtert die Datenpflege und unterstützt eine übersichtliche Struktur.

Ein weiteres häufig eingesetztes Muster ist das der „Liste“, das sich in der Modellierung von Angebot und Angebotsposition sowie Rechnung und Rechnungsposten wiederfindet. Diese Beziehungen stellen klassische Listenstrukturen dar, bei denen ein übergeordnetes Objekt (z. B. ein Angebot) mehrere gleichartige Unterobjekte (Positionen) umfasst. Die starke Komposition zwischen den Klassen sorgt dafür, dass Positionen immer in einem konkreten Zusammenhang stehen und nicht unabhängig existieren. Dieses Muster gewährleistet sowohl Konsistenz als auch klare Verantwortlichkeiten.

Die Klasse Lieferinformationen basiert auf dem Muster des „Koordinators“. In diesem Fall besteht eine n:m-Beziehung zwischen Produkten und Lieferanten, bei der zusätzliche Informationen wie Liefertermine oder Lieferbedingungen gespeichert werden müssen. Diese Informationen gehören jedoch zu keiner der beteiligten Klassen direkt. Durch die Einführung einer eigenen Koordinationsklasse können diese Daten modelliert werden, ohne die beteiligten Klassen unnötig zu verkomplizieren.

Auch das Muster „Rollen“ wurde sinnvoll eingesetzt. So kann eine Person verschiedene Rollen wie Mitarbeiter oder Geschäftspartner einnehmen. Diese Rollen werden durch spezialisierte Unterklassen abgebildet, während gemeinsame Eigenschaften wie Name oder Kontaktdaten in der Oberklasse bleiben. Diese Struktur erlaubt es, eine Person flexibel und gleichzeitig konsistent im System zu repräsentieren.

Darüber hinaus wurde bei der Modellierung von Lieferdaten das Prinzip der „Historie“ berücksichtigt. So unterscheidet die Klasse Liefertermin zwischen geplantem und tatsächlichem Lieferdatum. Auch wenn hier keine vollständige zeitliche Historienverwaltung erfolgt, unterstützt diese Unterscheidung die Nachvollziehbarkeit von Terminabweichungen und erleichtert zukünftige Erweiterungen des Systems um eine detailliertere Zeitverfolgung.

Diese bewusste Anwendung bewährter Analysemuster trägt wesentlich zur Robustheit, Verständlichkeit und Erweiterbarkeit unseres Modells bei und bildet eine stabile Grundlage für die weitere Systementwicklung.
